namespace BattleshipClient.Engine.Net
{
    enum PacketType
    {
        JoinRequest,
        JoinRequestAccepted,
        JoinRequestDenied,
        Prices,
        LandRequest,
        LandRequestAccepted,
        LandRequestDenied,
        InitiateShipPlacement,
        ShipRequest,
        ShipRequestAccepted,
        ShipRequestDenied,
        PurchaseRequest,
        PurchaseRequestAccepted,
        PurchaseRequestDenied,
        ActionRequest,
        ActionRequestAccepted,
        ActionRequestDenied,
        ReadyRequest,
        ReadyRequestAccepted,
        ReadyRequestDenied,
        AdvanceTurn,
        PlayerList,
        LandBroadcast,
        ActionBroadcast,
        ShipSunk,
        CutsceneFinished,
        Score,
        Oil,
        OutOfGame,
        EndOfGame,
        Disconnect
    }
}
